# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde53d5f19e7d81a93ef01d952e184892963deed666502616df8ea5d790c5809ec6dae4b2207bbec6caf99474a8229640c9b3e7d13001c0b65501823c420d40f

test:
  secret_key_base: 7ba91a5877aa2437e44d54de654a4b2a935daa469de1c36d005d3c639de3e1428e5733b7aaf82ca61a5a4e188a9225ce6c4c01e4ef0d5442ce7a5ecbd24e293e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
